/**
 * Agent Runner — Executes individual agents based on their role.
 * Phase 1: Uses mock responses. Phase 2: Will use Gemini API.
 */

function extractTopic(input) {
  if (typeof input === 'string') return input;
  if (input.userInput?.topic) return input.userInput.topic;
  if (input.userInput?.query) return input.userInput.query;
  if (typeof input.userInput === 'string') return input.userInput;
  if (input.cumulativeContext) {
    const match = input.cumulativeContext.match(/User Input:\s*({.*?})/s);
    if (match) {
      try {
        const parsed = JSON.parse(match[1]);
        return parsed.topic || parsed.query || 'the specified topic';
      } catch { /* ignore */ }
    }
  }
  return 'AI Agent Orchestration';
}

const MOCK = {
  researcher: (input) => {
    const t = extractTopic(input);
    return `## Research Findings: ${t}\n\n### Key Data Points\n1. **Market Size**: Estimated at $XX billion in 2026, CAGR of 15.3%.\n2. **Major Players**: TechCorp, InnovateLabs, DataDriven Inc. hold 45% market share.\n3. **Growth Drivers**: Digital transformation, AI adoption, regulatory changes.\n4. **Regional Analysis**: North America 38%, Asia-Pacific 31%.\n\n### Industry Trends\n- AI-powered automation in enterprise workflows\n- Sustainable and ethical AI solutions\n- Edge computing and decentralized architectures\n- Data privacy and governance frameworks\n\n### Sources: Gartner, McKinsey, Forrester, Bloomberg`;
  },
  analyst: (input) => {
    const t = extractTopic(input);
    return `## Analysis Report: ${t}\n\n### Executive Summary\nCritical patterns and strategic implications identified.\n\n### Key Insights\n1. **High Growth**: Enterprise AI automation — 40% budget increase\n2. **Underserved**: SMB segment with significant unmet demand\n3. **Moat**: Proprietary data pipelines show 2.3x better resilience\n\n### Risk Matrix\n| Risk | Probability | Impact |\n|------|-----------|--------|\n| Regulatory changes | Medium | High |\n| Market saturation | Low | Medium |\n| Tech disruption | Medium | High |\n\n### Recommendations\n1. Short-term: Product-market fit\n2. Medium-term: Adjacent markets\n3. Long-term: Platform ecosystem\n\nData Confidence: 85%`;
  },
  writer: (input) => {
    const t = extractTopic(input);
    return `# ${t} — Market Research Report\n\n## 1. Introduction\nComprehensive analysis of ${t} for strategic decision-making.\n\n## 2. Market Overview\nRapid transformation driven by technological innovation. Market poised for significant growth.\n\n## 3. Competitive Landscape\nMix of established players and startups. Top three hold 45% share.\n\n## 4. Strategic Analysis\n**Strengths**: Strong tech foundation, growing demand\n**Opportunities**: Untapped SMB market, cross-industry AI applications\n\n## 5. Recommendations\nPhased market entry prioritizing enterprise customers.\n\n## 6. Conclusion\nCompelling opportunities for innovators. Early movers will capture significant share.\n\n---\n*Report generated by AgentFlow*`;
  },
  critic: () => {
    return `## Quality Review\n\n### Overall: ✅ APPROVED (8.5/10)\n\n### Strengths\n- Well-structured with clear logical flow\n- Relevant, supporting data points\n- Actionable, time-bound recommendations\n\n### Improvements Suggested\n- Update to Q2 2026 data\n- Add inline citations\n- Deeper competitor profiles\n\n### Fact-Check: All key figures verified ✅\n\n**Verdict: Approved for delivery.**`;
  },
  custom: (input) => {
    const t = extractTopic(input);
    return `## Custom Agent Output\n\nProcessed "${t}" successfully. Results ready for downstream processing.`;
  },
};

export async function runAgent(role, input) {
  const r = role.toLowerCase().trim();
  const fn = MOCK[r] || MOCK.custom;
  return fn(input);
}
